name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true

    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and build dependencies
        run: npm install && npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          install_command: npm install && npm run build
          build_command: npm run build-storybook
          path: storybook-static

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "docs/CHANGELOG.md"
          create-summary: true
          skip-ci: false
          skip-on-empty: false

      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
