name: Release
on:
  release:
    types: [published]

  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write

    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hattaalfaritzy"

      - name: Install and build dependencies
        run: npm install && npm run build

      - name: Build Storybook
        run: npm run build-storybook

      # create release CHANGELOG
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.G_TOKEN }}
          output-file: "docs/CHANGELOG.md"
          create-summary: true
          skip-ci: false
          skip-on-empty: false

      # create release new tag
      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      # publish package to npm after create release new version and tag
      - name: Publish package to npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}

      # create semantic release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
        run: npx semantic-release
